package dialogue;


/**
* dialogue/ConnectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from connection.idl
* samedi 3 janvier 2015 11 h 54 CET
*/

public interface ConnectionOperations 
{
  dialogue.Emitter connect (String pseudo, dialogue.Receiver rcv);
  void disconnect (String pseudo) throws dialogue.notExistingPseudo;
} // interface ConnectionOperations
