package dialogue;


/**
* dialogue/Connection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from connection.idl
* samedi 3 janvier 2015 11 h 54 CET
*/

public interface Connection extends ConnectionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Connection
