package dialogue;


/**
* dialogue/Emitter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from emitter.idl
* samedi 3 janvier 2015 12 h 03 CET
*/

public interface Emitter extends EmitterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Emitter
