package dialogue;

/**
 * dialogue/EmitterHolder.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from emitter.idl samedi 3 janvier 2015 12 h 03 CET
 */

public final class EmitterHolder implements org.omg.CORBA.portable.Streamable {
    public dialogue.Emitter value = null;

    public EmitterHolder() {
    }

    public EmitterHolder(dialogue.Emitter initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = dialogue.EmitterHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        dialogue.EmitterHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return dialogue.EmitterHelper.type();
    }

}
