package dialogue;


/**
* dialogue/notExistingPseudo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from receiver.idl
* samedi 3 janvier 2015 12 h 04 CET
*/

public final class notExistingPseudo extends org.omg.CORBA.UserException
{
  public String detail = null;

  public notExistingPseudo ()
  {
    super(notExistingPseudoHelper.id());
  } // ctor

  public notExistingPseudo (String _detail)
  {
    super(notExistingPseudoHelper.id());
    detail = _detail;
  } // ctor


  public notExistingPseudo (String $reason, String _detail)
  {
    super(notExistingPseudoHelper.id() + "  " + $reason);
    detail = _detail;
  } // ctor

} // class notExistingPseudo
