package dialogue;

/**
 * dialogue/Receiver.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from receiver.idl samedi 3 janvier 2015 12 h 04 CET
 */

public interface Receiver extends ReceiverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface Receiver
