package dialogue;


/**
* dialogue/ReceiverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from receiver.idl
* samedi 3 janvier 2015 12 h 04 CET
*/

public interface ReceiverOperations 
{
  void receive (String from, String message);
  void initClients (String[] clients);
  void addClient (String client) throws dialogue.notExistingPseudo;
  void remClient (String client) throws dialogue.notExistingPseudo;
} // interface ReceiverOperations
