package dialogue;


/**
* dialogue/ReceiverPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from receiver.idl
* samedi 3 janvier 2015 12 h 04 CET
*/

public abstract class ReceiverPOA extends org.omg.PortableServer.Servant
 implements dialogue.ReceiverOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("receive", new java.lang.Integer (0));
    _methods.put ("initClients", new java.lang.Integer (1));
    _methods.put ("addClient", new java.lang.Integer (2));
    _methods.put ("remClient", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dialogue/Receiver/receive
       {
         String from = in.read_string ();
         String message = in.read_string ();
         this.receive (from, message);
         out = $rh.createReply();
         break;
       }

       case 1:  // dialogue/Receiver/initClients
       {
         String clients[] = dialogue.clientsHelper.read (in);
         this.initClients (clients);
         out = $rh.createReply();
         break;
       }

       case 2:  // dialogue/Receiver/addClient
       {
         try {
           String client = in.read_string ();
           this.addClient (client);
           out = $rh.createReply();
         } catch (dialogue.notExistingPseudo $ex) {
           out = $rh.createExceptionReply ();
           dialogue.notExistingPseudoHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // dialogue/Receiver/remClient
       {
         try {
           String client = in.read_string ();
           this.remClient (client);
           out = $rh.createReply();
         } catch (dialogue.notExistingPseudo $ex) {
           out = $rh.createExceptionReply ();
           dialogue.notExistingPseudoHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dialogue/Receiver:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Receiver _this() 
  {
    return ReceiverHelper.narrow(
    super._this_object());
  }

  public Receiver _this(org.omg.CORBA.ORB orb) 
  {
    return ReceiverHelper.narrow(
    super._this_object(orb));
  }


} // class ReceiverPOA
