package dialogue;


/**
* dialogue/ReceiverHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from receiver.idl
* samedi 3 janvier 2015 12 h 04 CET
*/

abstract public class ReceiverHelper
{
  private static String  _id = "IDL:dialogue/Receiver:1.0";

  public static void insert (org.omg.CORBA.Any a, dialogue.Receiver that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dialogue.Receiver extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (dialogue.ReceiverHelper.id (), "Receiver");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dialogue.Receiver read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ReceiverStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dialogue.Receiver value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static dialogue.Receiver narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dialogue.Receiver)
      return (dialogue.Receiver)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dialogue._ReceiverStub stub = new dialogue._ReceiverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static dialogue.Receiver unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dialogue.Receiver)
      return (dialogue.Receiver)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dialogue._ReceiverStub stub = new dialogue._ReceiverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
